<?php
/**
 * API Generation for the framework
 * 
 * PHP version 5.4
 * 
 * @category  API
 * @package   Boiler
 * @author    Will Tinsdeall <will.tinsdeall@mercianlabels.com>
 * @copyright 2013 Mercian Labels
 * @license   http://www.mercianlabels.com All Rights Reserved
 * @link      http://www.mercianlabels.com
 */
namespace Controller\Api;


/**
 * Autogenerated class for API access to the model \\Model\\$class
 * 
 * PHP version 5.4
 *
 * @category API
 * @package  Boiler
 * @author   Will Tinsdeall <will.tinsdeall@mercianlabels.com>
 * @license  All Rights Reserved
 * @version  GIT: \$Id$
 * @link     http://www.mercianlabels.com
 *
 */
abstract class ModelController extends \System\Controller\Api\ModelController {
	
}